var CATS = {
  "ball-cat":                {orientation: "both", horizontalPercentage: "40%"},
  "banana-cat":              {orientation: "both", horizontalPercentage: "33%"},
  "basket-cat":              {orientation: "both", horizontalPercentage: "40%"},
  "biting-cub":              {orientation: "both", horizontalPercentage: "55%"},
  "biting-cub-2":            {orientation: "both", horizontalPercentage: "50%"},
  "box-cat":                 {orientation: "both", horizontalPercentage: "33%"},
  "box-cat-2":               {orientation: "both", horizontalPercentage: "50%"},
  "box-cat-3":               {orientation: "both", horizontalPercentage: "45%"},
  "brush-cat":               {orientation: "both", horizontalPercentage: "50%"},
  "bucket-cat":              {orientation: "horizontal"},
  "bunny-cat":               {orientation: "horizontal"},
  "cat-catching-plush":      {orientation: "horizontal"},
  "cat-hugs-his-teddy-bear": {orientation: "both", horizontalPercentage: "66%"},
  "confused-cat":            {orientation: "horizontal"},
  "cup-cat":                 {orientation: "both", horizontalPercentage: "50%"},
  "dancing-cat":             {orientation: "both", horizontalPercentage: "55%"},
  "ear-twitch":              {orientation: "vertical"},
  "fat-cat":                 {orientation: "horizontal"},
  "lazy-cat":                {orientation: "horizontal"},
  "lion-cat":                {orientation: "both", horizontalPercentage: "45%"},
  "lizard-cat":              {orientation: "both", horizontalPercentage: "33%"},
  "many-petters":            {orientation: "both", horizontalPercentage: "33%"},
  "paw-licking":             {orientation: "both", horizontalPercentage: "25%"},
  "playful-kitten":          {orientation: "both", horizontalPercentage: "60%"},
  "quiver-cat":              {orientation: "horizontal"},
  "sewing-cat":              {orientation: "both", horizontalPercentage: "50%"},
  "sleepy-cat":              {orientation: "both", horizontalPercentage: "50%"},
  "sleepy-cat-2":            {orientation: "both", horizontalPercentage: "33%"},
  "sleepy-cat-3":            {orientation: "both", horizontalPercentage: "55%"},
  "surprise-cat":            {orientation: "both", horizontalPercentage: "60%"},
  "tail-licking-kitty":      {orientation: "vertical"},
  "tail-wag":                {orientation: "horizontal"},
  "tongue-out":              {orientation: "both", horizontalPercentage: "50%"},
  "tummy-scratch":           {orientation: "horizontal"},
  "two-cats":                {orientation: "horizontal"},
  "wobble-cat":              {orientation: "both", horizontalPercentage: "55%"},
  "yawning-cat":             {orientation: "vertical"},
  "yawning-lion-cat":        {orientation: "both", horizontalPercentage: "50%"}
};

var CAT_NAMES = Object.keys(CATS);
